version: '3.8'

services:
  ######################
  # Frontend
  #####################
  frontend:
    container_name: adamoore-net-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/local/app